### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by danyill** [JakobVogelsang/oscd-publisher#2]
Thank you for the opportunity to provide some early feedback.
This feedback is based on ac3b4b90

As always, feel free to use what you think has value and let the rest go :wink: 

Some of these comments may be at features yet to be implemented or where I haven't understood the direction. Either way, happy to discuss.

Overall this is looking amazing and could easily be the cleanest, simplest editor I've seen anywhere.

1. I get errors after an `npm i` on Node 18:
    ```
    12:58 $ npm i

    > oscd-save@0.0.0 prepublish
    > tsc && npm run analyze -- --exclude dist

    node_modules/@material/base/observer-foundation.d.ts:25:75 - error TS2344: Type 'Adapter' does not satisfy the constraint '{}'.

    25 export declare class MDCObserverFoundation<Adapter> extends MDCFoundation<Adapter> {
                                                                                ~~~~~~~

    node_modules/@material/base/observer-foundation.d.ts:25:44
        25 export declare class MDCObserverFoundation<Adapter> extends MDCFoundation<Adapter> {
                                                    ~~~~~~~
        This type parameter might need an `extends {}` constraint.


    Found 1 error in node_modules/@material/base/observer-foundation.d.ts:25
    ```
    I resolved this using the advice here https://github.com/mobxjs/mobx/issues/3532#issuecomment-1304080708

2. When editing the dataset, re-ordering items by dragging and dropping would be a very nice user convenience.

3. In the DataSet view a divider between the dataset and the top portion may make it clearer where the save button belongs (the top, not the bottom). Why do we need a save button?

4. In the DataSet view, if I have already clicked on an attribute or a DO when I click add, a helpful user convenience might be that they are taken to the same view within the data model (so the user doesn't have difficult when they decide I just need to add another attribute to this). 

5. Similarly if I choose to add a data attribute or data object should it be immediately below any item which is already activated? Users will get it wrong once and then they'll like it, but if they have drag and drop they probably won't mind. Otherwise and perhaps anyway any filter needs to be removed or somehow extended so the user action is clear after the add action is complete (i.e. so you can see the new FCDA/FCDO in the list).

7. I really like: the new dataset button, the delete dataset button, the delete FCDA/FCDO. The view feels clean and uncomplicated. To improve it more, however the delete buttons the add new could be controlled by "hover CSS" along the lines of:
    ```css
    mwc-list-item:hover .delete-or-add-new-thing {
      visibility: visible;
      opacity: 1;
      transition: visibility 0s, opacity 0.5s linear;
    }

    .delete-or-add-new-thing {
      visibility: hidden;
      opacity: 0;
    }
    ```
9.  I am not sure what `PUBLISHER.SELECTBUTTON.DATASET` is intended to do. But on mobile being able to scope to an IED up front would prevent keyboard interaction from being required (basically a restatement of [#1144](https://github.com/openscd/open-scd/issues/1144) as a general principle for design!).

10. For the dataset view if there are no IEDs perhaps the search bar of the filtered-list shouldn't even show? Same applies to other views (Report/GOOSE/SampledValue).
    ![image](https://user-images.githubusercontent.com/674783/215229360-bcb7fa4e-2abc-4a82-8e0f-93f4ac209402.png)

11. Perhaps, similar to what I did recently for ExtRefs, the identity string of the parent should be used to remove duplicated information, e.g. the following:
    ![image](https://user-images.githubusercontent.com/674783/215229583-ceb40886-ac51-47fe-b8f6-60cd56327da3.png)
    The idea being that this is adding context/namespace/location/path and the content is described using the first line. This also applied to the second line in the DataSet 

12. It would be nice to see some "Pro mode" edit buttons at some stage.

13. I know it doesn't affect Macs, but finding a way to remove the vertical scrollbar would be nice. :stuck_out_tongue_winking_eye: 
    ![image](https://user-images.githubusercontent.com/674783/215230086-f961d62b-d954-49f4-8dc9-2356ab4b780f.png)

14. I couldn't add FCDO or FCDA items (using either the oscd-core demo or open-scd, I guess that means this functionality is not yet available?).

15. More soon !

**Comment by danyill** [comment]
I think the divider looks good and 


Here's a few more things:

1. If I try to open a new file in the publisher plugin, and a file with the same file name is open, nothing happens (this just a local testing using core).

1. I notice that with the attached file the update dataset button is missing: 
    [XAT_Prot1_Demo.scd.zip](https://github.com/JakobVogelsang/oscd-publisher/files/10528659/XAT_Prot1_Demo.scd.zip)
    
    We seem to use `?disabled=${!!findCtrlBlockSubscription(this.selectedGseControl)` but this doesn't work so well is there is no subscriptions. I think somehow this is the wrong method to call.
    
    ![image](https://user-images.githubusercontent.com/674783/215297336-e7000eb5-20c6-4692-82a8-bd60d2bea04b.png)

1. Adding FCDOs and FCDAs doesn't refresh automatically but can be forced by changing e.g. the desc toggle bar.
    
    ![image](https://user-images.githubusercontent.com/674783/215297348-f9dd3fb1-7c42-487a-9426-d4608b370946.png)

1. If I create a new GOOSE in the GOOSE editor and then try and delete it I get an error:

    ```
    controlBlocks.ts:10 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getAttribute')
        at findCtrlBlockSubscription (controlBlocks.ts:10:44)
        at GseControlEditor.renderElementEditorContainer (gse-control-editor.ts:145:29)
        at GseControlEditor.render (gse-control-editor.ts:237:45)
        at GseControlEditor.update (lit-element.ts:160:24)
        at GseControlEditor.update (gse-control-editor.ts:49:11)
        at GseControlEditor.performUpdate (reactive-element.ts:1327:14)
        at GseControlEditor.scheduleUpdate (reactive-element.ts:1259:17)
        at GseControlEditor.__enqueueUpdate (reactive-element.ts:1231:25)
    ```

1. It would be nice to disable spellchecking for some fields using the [`spellcheck`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck) attribute - only obvious one here is the MAC-Address:

    ![image](https://user-images.githubusercontent.com/674783/215297461-3a21f2e9-4757-41ac-8694-208fc69fc426.png)

**Comment by danyill** [comment]
Incidentally there is a nice icon we could possibly use to show that a dataset/GSEControl/SampledValueControl is linked to an IED that I discovered by accident today:

![image](https://user-images.githubusercontent.com/674783/216760779-7994862c-14c9-49fc-84b8-c59c6ace75ed.png)

**Comment by JakobVogelsang** [comment]
@danyill would you mind me closing this repo? And would you be so kind to take over open issues to its fork on OpenEnergyTools?
